[project]
name = "matr1x"
version = "7.1.0"
description = "Python package for data acquisition and measurement control"
requires-python = ">=3.6"
dependencies = [
  "h5py",
  "natsort",
  "numpy",
  "pymeasure",
  "pyserial",
  "pyvisa",
  "pyvisa-py",
  "urwid>2.0",
  "wrapt",
]
[project.optional-dependencies]
spi = ["spidev", "RPi"]
# comment out PyQt5 dependency on Debian/Raspian 10 (or older)
qt5 = ["pyqtgraph >= 0.11.0", "PyQt5 >= 5.14.0"]
qt6 = ["pyqtgraph >= 0.11.0", "PyQt6"]
standa = ["PyUSMC", "pyximc"]

[project.scripts]
matrix = "matr1x.scripts.matrix:main"
matrix_gui = "matr1x.scripts.matrix_gui:main"

[project.gui-scripts]
sweep_generator = "matr1x.scripts.sweep_generator:main"
matrix_script = "matr1x.scripts.matrix_script:main"
matrix_preview = "matr1x.scripts.matrix_preview:main"
control_dummy = "matr1x.control.control_dummy:main"


[project.urls]
homepage = "https://github.com/andythomas/IFW_software"

[build-system]
# use flit since setuptools does currently not support PEP660
requires = ["flit_core >=3.6,<4"]
build-backend = "flit_core.buildapi"

[tool.pytest.ini_options]
addopts = "--capture=tee-sys --show-capture=all"
