[project]
name = "matr1x"
version = "8.1.0"
description = "Python package for data acquisition and measurement control"
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
]
dependencies = [
    "tomli ; python_version < '3.11'",               # imported in matr1x
    "tomli-w",                                       # imported in matr1x
    "pydantic >= 2.0",                               # imported in matr1x
    "h5py >= 2.7.0",                                 # imported via util,
    "numpy",                                         # imported via util
    "pyobjc ; platform_system == 'Darwin'",          # imported via util
    "decorator>=5.2.1",                              # imported via util
    "pandas >= 1.0.0",                               # imported via eval,
    "psutil",                                        # imported via control/util
    "pyqtgraph >= 0.11.0",                           # needed for GUI apps
    "PySide6",                                       # needed for GUI apps
    "PySide6 >= 6.5.0 ; platform_system == 'Windows'", # needed for GUI apps
    "pygit2 >= 1.16",                                # needed for GUI apps
    "wrapt>2.0",                                     # needed for GUI apps
    "urwid>2.0",                                     # needed for GUI apps
    "monaco-assets>=0.5.1",                          # needed for matrix script
    "ruff>=0.13.0",                                  # needed for matrix script
    "pymeasure",                                     # shared by several device drivers
    "pyserial",                                      # shared by several device drivers
    "pyvisa",                                        # shared by several device drivers
    "pyvisa-py",                                     # shared by several device drivers
    "minimalmodbus",                                 # shared by several device drivers
]

[project.optional-dependencies]
elab = ["elabapi_python", "jinja2"] # for the electronic notebook
ppms = [
    "MultiPyVu >= 3.6.1", # for matr1x/devices/quantumdesign/ppms,
]
smbus = ["smbus3 >= 0.5.5"]

[project.scripts]
matrix = "matr1x.scripts.matrix:main"
matrix-gui = "matr1x.scripts.matrix_gui:main"

[project.gui-scripts]
sweep-generator = "matr1x.scripts.sweep_generator:main"
matrix-script = "matr1x.scripts.matrix_script:main"
matrix-preview = "matr1x.scripts.matrix_preview:main"
control-dummy = "matr1x.control.control_dummy:main"

[project.urls]
homepage = "https://github.com/andythomas/IFW_software"

[build-system]
# use flit since setuptools does currently not support PEP660
requires = ["flit_core >=3.6,<4"]
build-backend = "flit_core.buildapi"

[tool.pytest.ini_options]
addopts = "--capture=tee-sys --show-capture=all"
env = [
    "QT_QPA_PLATFORM=offscreen",
    "QT_QUICK_BACKEND=software",
]

[tool.pyrefly]
project-includes = [
    "matr1x"
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-env>=1.1.5",
    "ty>=0.0.1-alpha.20",
    "sphinx>=7.4.7",
    "pytest-qt>=4.5.0",
    "pytest-timeout>=2.4.0",
]
