[project]
name = "matr1x-measurements"
version = "8.4.1"
description = "Python package for data acquisition and measurement control"
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
]
dependencies = [
    "tomli ; python_version < '3.11'",               # imported in matr1x
    "tomli-w",                                       # imported in matr1x
    "pydantic >= 2.0",                               # imported in matr1x
    "h5py >= 2.7.0",                                 # imported via util,
    "numpy",                                         # imported via util
    "pyobjc ; platform_system == 'Darwin'",          # imported via util
    "decorator >= 5.2.1",                            # imported via util
    "pandas >= 1.0.0",                               # imported via eval,
    "psutil",                                        # imported via control/util
    "pyqtgraph >= 0.11.0",                           # needed for GUI apps
    "PySide6",                                       # needed for GUI apps
    "PySide6 >= 6.5.0 ; platform_system == 'Windows'", # needed for GUI apps
    "pygit2 >= 1.16",                                # needed for GUI apps
    "pygit2 >= 1.19; python_version >= '3.14'",      # needed for GUI apps Py 3.14+
    "wrapt>2.0",                                     # needed for GUI apps
    "urwid>2.0",                                     # needed for GUI apps
    "script2bundle >= 0.3.0 ; platform_system == 'Darwin'", # needed for GUI apps for desktop integration
    "monaco-assets >= 0.5.1",                        # needed for matrix script
    "ruff >= 0.15.22",                               # needed for matrix script
    "ty == 0.0.30",                                  # needed for matrix script
    "pymeasure >= 0.16.0",                           # shared by several device drivers
    "pyserial",                                      # shared by several device drivers
    "pyvisa",                                        # shared by several device drivers
    "pyvisa-py",                                     # shared by several device drivers
    "minimalmodbus",                                 # shared by several device drivers
]

[project.optional-dependencies]
elab = ["elabapi_python >= 5.3.0", "jinja2"] # for the electronic notebook
ppms = [
    "MultiPyVu >= 3.6.1", # for matr1x/devices/quantumdesign/ppms,
]
smbus = ["smbus3 >= 0.5.5"]

[project.scripts]
matrix = "matr1x.scripts.matrix:main"
matrix-di = "matr1x.scripts.matrix_di:main"

[project.gui-scripts]
matrix-gui = "matr1x.scripts.matrix_gui:main"
sweep-generator = "matr1x.scripts.sweep_generator:main"
matrix-script = "matr1x.scripts.matrix_script:main"
matrix-preview = "matr1x.scripts.matrix_preview:main"
control-dummy = "matr1x.control.control_dummy:main"

[project.urls]
Homepage = "https://github.com/andythomas/matr1x"
Documentation = "https://andythomas.github.io/matr1x/"

[build-system]
# use flit since setuptools does currently not support PEP660
requires = ["flit_core >=3.6,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "matr1x"

[tool.pytest.ini_options]
addopts = "--capture=tee-sys --show-capture=all"
timeout = 30
timeout_method = "thread"
session_timeout = 210
env = [
    "QT_QPA_PLATFORM=offscreen",
    "QT_QUICK_BACKEND=software",
]

[tool.pyrefly]
project-includes = [
    "matr1x"
]

[tool.ty.src]
include = ["matr1x"]


[tool.ruff]
line-length = 99       # max per pep8

[tool.ruff.lint]
extend-select = [
    'D',        # pydocstyle (docstring formatting)
    'A',        # flake8 builtins (Python builtins being used as variables or parameters.)
    'I',        # isort (sort imports)
    'PLW0602',  # unassigned global variable
    'W505',     # doc line too long
    'E501',     # line too long
    'UP',       # use most modern code allowed by lowest python version
    'PTH',      # use modern pathlib methods if possible
    'LOG',      # look for correct logging
    'G',        # look for correct log formatting
    'INP001',   # provide __init__ for packages
    'PIE',      # use flake8-pie rules (unnecessary code pieces)
    'PYI',      # use flake8-pyi rules (type hinting helpers)
    'SIM300',   # use human readable comparisons (yoda condition)
    # disable to mark required prints and reenable after cleanup finished
    #'RUF100',   # no not allow unused noqa
    'T201'      # do not use print statements
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["INP001", "T201"]
"docs/conf.py" = ["PTH"]
"docs/**" = ["INP001"]
"matr1x/devices/**" = ["T201"]
"matr1x/systems/system_elabftw.py" = ["T201"]

[tool.ruff.lint.pycodestyle]
max-line-length = 100
max-doc-length = 100  # should be max 72 per pep8

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version"
]
branch = "main"
build_command = "pip install flit && flit build --no-use-vcs"

[tool.semantic_release.changelog]
exclude_commit_patterns = [
    '''^refactor''',
    '''^test''',
    '''^chore''',
    '''^ci''',
]

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true


[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-env>=1.1.5",
    "sphinx>=7.4.7",
    "pytest-qt>=4.5.0",
    "pytest-timeout>=2.4.0",
]
