[matr1x]
datetime_format = "%Y-%m-%dT%H:%M:%S"
logging_directory = "~/logs"
logging_format = "%(asctime)s,%(msecs)03d,%(levelname)s,%(name)s: %(message)s"
users_directory = "~/users"
systems_directory = "<pkgroot>/systems"

[matr1x.scripts.matrix-script]
script_path = ""
store_script_in_datafile = false

[matr1x.devices.visadevice]
cmdpers = 30
pts = false
visadebug = false

[matr1x.install]
root_path = "core_library/"
create_directories = false
desktopintegration = true
pip_options = "-q --log install.log"
